config/routes.rb
Rails.application.routes.draw do

  get 'activities/index'

  resources :participations

  resources :activities
  resources :progresses
  resources :comments
  resources :challenges
  resources :user_profile

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations'}
  resources :users, :only => [:show]

  root 'homepage#index'

end

app/models/participation.rb
class Participation < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :user
  belongs_to :challenge
  has_many :progresses, :dependent => :destroy

  validates :challenge, presence: true
  validates :user, presence: true

  def total_gain
    progresses.sum(:gain)
  end

end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  include Devise::Controllers::Helpers
  before_action :set_participation, only: [:show, :edit, :update, :destroy]

  # GET /participations
  # GET /participations.json
  def index
    @participations = Participation.all
  end

  # GET /participations/1
  # GET /participations/1.json
  def show
  end

  # GET /participations/new
  def new
    @participation = Participation.new
  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations
  # POST /participations.json
  def create
    @participation = Participation.new(participation_params)
    @participation.user = current_user
    @participation.challenge_id = params[:challenge_id]
    @participation.status = 1
    respond_to do |format|
      if @participation.save
        @challenge = Challenge.find(params[:challenge_id])
        @participation.create_activity :create, owner: current_user
        format.html { redirect_to @challenge, notice: 'Participation was successfully created.' }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participations/1
  # PATCH/PUT /participations/1.json
  def update
    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_to @participation, notice: 'Participation was successfully updated.' }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1
  # DELETE /participations/1.json
  def destroy
    @challenge = @participation.challenge
    @participation.destroy
    respond_to do |format|
      format.html { redirect_to @challenge, notice: 'Participation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participation_params
      #params.require(:participation).permit(:user_id, :challenge_id)
    end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_form.html.erb
<%= form_for(@participation) do |f| %>
  <% if @participation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
      <% @participation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :challenge_id %><br>
    <%= f.text_field :challenge_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participations/_participation.html.erb
<div class="well well-sm">
  <div>

        <strong><%= participation.user.name if participation.user %></strong>


    <% if participation.challenge.distance.present?
         if participation.challenge.distance > participation.total_gain && participation.total_gain > 0
         current_gain = ( participation.total_gain.to_f/participation.challenge.distance.to_f) * 100 %>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="<%= participation.total_gain %>" aria-valuemin="0"
               aria-valuemax="100" style="width:<%= current_gain %>%">
            <%= participation.total_gain %> meters
          </div>
        </div>
       <% elsif participation.total_gain > participation.challenge.distance %>
        <div class="progress">
          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0"
        aria-valuemax="100" style="width:100%">
            Done!
        </div>
        </div>
        <% else %>
           <br> Add a progress to see a progress bar!
        <% end
       else%>
    Tell the owner to add a distance to the challenge!
    <% end %>
  </div>
</div>

app/views/participations/edit.html.erb
<h1>Editing participation</h1>

<%= render 'form' %>

<%= link_to 'Show', @participation %> |
<%= link_to 'Back', participations_path %>

app/views/participations/index.html.erb
<h1>Listing participations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Challenge</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participations.each do |participation| %>
      <tr>
        <td><%= participation.user %></td>
        <td><%= participation.challenge %></td>
        <td><%= link_to 'Show', participation %></td>
        <td><%= link_to 'Edit', edit_participation_path(participation) %></td>
        <td><%= link_to 'Destroy', participation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participation', new_participation_path %>

app/views/participations/new.html.erb
<h1>New participation</h1>

<%= render 'form' %>

<%= link_to 'Back', participations_path %>

app/views/participations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @participation.user %>
</p>

<p>
  <strong>Challenge:</strong>
  <%= @participation.challenge %>
</p>

<%= link_to 'Edit', edit_participation_path(@participation) %> |
<%= link_to 'Back', participations_path %>