config/routes.rb
Rails.application.routes.draw do

  get 'activities/index'

  resources :participations

  resources :activities
  resources :progresses
  resources :comments
  resources :challenges
  resources :user_profile

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations'}
  resources :users, :only => [:show]

  root 'homepage#index'

end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController
  include Devise::Controllers::Helpers

  before_action :set_progress, only: [:show, :edit, :update, :destroy]

  # GET /progresses
  # GET /progresses.json
  def index
    @progresses = Progress.all
  end

  # GET /progresses/1
  # GET /progresses/1.json
  def show
  end

  # GET /progresses/new
  def new
    @progress = Progress.new
  end

  # GET /progresses/1/edit
  def edit
  end

  # POST /progresses
  # POST /progresses.json
  def create
    @progress = Progress.new(progress_params)
    @progress.user = current_user
    @challenge = Challenge.find(progress_params[:challenge_id])
    @progress.participation = @challenge.participations.find_by(:user_id => current_user.id)
    respond_to do |format|
      if @progress.save
        @progress.create_activity :create, owner: current_user
        format.html { redirect_to @challenge, notice: 'Progress was successfully created.' }
        format.json { render :show, status: :created, location: @progress }
      else
        format.html { render :new }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1
  # PATCH/PUT /progresses/1.json
  def update
    respond_to do |format|
      if @progress.update(progress_params)
        @challenge = Challenge.find(progress_params[:challenge_id])
        format.html { redirect_to @challenge, notice: 'Progress was successfully updated.' }
        format.json { render :show, status: :ok, location: @progress }
      else
        format.html { render :edit }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progresses/1
  # DELETE /progresses/1.json
  def destroy
    @progress.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Progress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress
      @progress = Progress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progress_params
      params.require(:progress).permit(:gain, :challenge_id)
    end
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/views/progresses/_form.html.erb
<%= form_for(@progress) do |f| %>
  <% if @progress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@progress.errors.count, "error") %> prohibited this progress from being saved:</h2>

      <ul>
      <% @progress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gain %><br>
    <%= f.number_field :gain %>
  </div>
  <%= f.hidden_field :challenge_id, :value => params[:challenge_id] %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/progresses/_progress.html.erb
<% if progress.user == current_user %>
<%= link_to edit_progress_path(progress, :challenge_id => @challenge.id), class: 'btn btn-xs' do %>
<i class="glyphicon glyphicon-edit"></i>
<% end %>
<%= link_to progress, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs' do %>
<i class="glyphicon glyphicon-remove"></i>
<% end
end%>
<div class="well well-sm">
    <div>
        <% if @challenge.sport == 0 %>
          <strong><%= progress.user.name if progress.user %></strong>
          swam <%= progress.gain %> meters!
        <% else @challenge.sport == 1 %>
          <strong><%= progress.user.name if progress.user %></strong>
          ran <%= progress.gain %> meters!
          <% end %>
    </div>
</div>

app/views/progresses/edit.html.erb
<h1>Editing progress</h1>

<%= render 'form' %>

<% challenge = Challenge.find_by(:id => params['challenge_id']) %>
<%= link_to 'Back', challenge %>

app/views/progresses/index.html.erb
<h1>Listing progresses</h1>

<table>
  <thead>
    <tr>
      <th>Gain</th>
      <th>Challenge</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @progresses.each do |progress| %>
      <tr>
        <td><%= progress.gain %></td>
        <td><%= progress.challenge.name if progress.challenge %></td>
        <td><%= link_to 'Show', progress %></td>
        <td><%= link_to 'Edit', edit_progress_path(progress) %></td>
        <td><%= link_to 'Destroy', progress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Progress', new_progress_path %>

app/views/progresses/new.html.erb
<h1>New progress</h1>

<%= render 'form' %>
<% challenge = Challenge.find_by(:id => params['challenge_id']) %>
<%= link_to 'Back', challenge %>

app/views/progresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gain:</strong>
  <%= @progress.gain %>
</p>

<p>
  <strong>Challenge:</strong>
  <%= @progress.challenge.name if @progress.challenge %>
</p>

<%= link_to 'Edit', edit_progress_path(@progress) %> |
<%= link_to 'Back', progresses_path %>