config/routes.rb
Rails.application.routes.draw do

  get 'activities/index'

  resources :participations

  resources :activities
  resources :progresses
  resources :comments
  resources :challenges
  resources :user_profile

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations'}
  resources :users, :only => [:show]

  root 'homepage#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title>Compete</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div data-spy="affix" data-offset-top="0" data-offset-bottom="200">
    <div id="nav">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>
       <%= link_to 'Compete', root_path, :class => 'navbar-brand'%>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-left">
          <% if user_signed_in? %>
            <li <%= 'class="active"'.html_safe if current_page? root_path %>><%= link_to 'Home', root_path %></li>
            <li <%= 'class="active"'.html_safe if current_page? challenges_path %>><%= link_to 'Challenges', challenges_path %></li>
            <li <%= 'class="active"'.html_safe if current_page? new_challenge_path %>><%= link_to 'New Challenge', new_challenge_path %></li>

          <% else %>

          <% end %>
              
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                  <li><%= link_to 'Profile', user_profile_path(current_user.id), :class => 'navbar-link' %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            <% else %>
                  <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                  <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            <% end %>
           </ul>
          </div>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

<div class="container">


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</div>
</body>
</html>